CREATE TABLE [ROM].[RoomAddress]
(
	[RoomAddressId] INT NOT NULL IDENTITY,
	[RoomId] UNIQUEIDENTIFIER NOT NULL,
	[Address1] NVARCHAR(100) NOT NULL,
	[Address2] NVARCHAR(100) NULL,
	[Address3] NVARCHAR(100) NULL,
	[City] NVARCHAR(100) NOT NULL,
	[State] NVARCHAR(100) NOT NULL,
	[Zip] NVARCHAR(100) NOT NULL,
	[IsActive] BIT NOT NULL,
	[UpdatedDate] DATETIME NULL,
	[UpdatedBy] NVARCHAR(100) NULL,
	
	CONSTRAINT PK_Room_Address_Id PRIMARY KEY(RoomAddressId),
	CONSTRAINT FK_Rooms_Id FOREIGN KEY(RoomId) REFERENCES [ROM].[Rooms](RoomId),
)
